-- Test try/catch/throw code

type error is noError or simpleError(#string);
  
{}
thrower(){
  __#outStr(__#logFile,"start the throw\n");
  X:error is simpleError("a stone's throw");
  throw X;
  __#outStr(__#logFile,"after a throw\n");
 };

{thrower}
caller(){
  __#outStr(__#logFile,"calling thrower\n");
  thrower();
  __#outStr(__#logFile,"thrower did not throw\n");
};

{caller}
catcher(){
  try{
    caller();
    __#outStr(__#logFile,"should not be here\n");
  }
  catch{
    noError do       
      __#outStr(__#logFile,"no error here\n");
    simpleError(S:#string) do{
      __#outStr(__#logFile,"got error ");
      __#outStr(__#logFile,S);
      __#outStr(__#logFile," now\n");
    }
  }
  default X:error do 
    __#outStr(__#logFile,"default error here\n");
};

{catcher}
main(){
  __#outStr(__#logFile,"start the catch\n");
  catcher();
  __#outStr(__#logFile,"after the catch\n");
}
